AR = 'C:\\MinGW\\bin\\ar.exe'
ARFLAGS = 'rcs'
BINDIR = 'C:\\users\\adrian~1\\appdata\\local\\temp/bin'
CC_VERSION = ('4', '8', '1')
CPPPATH_ST = '-I%s'
CXX = ['C:\\MinGW\\bin\\g++.exe']
CXXFLAGS = ['-g', '-Wall', '-shared']
CXXFLAGS_MACBUNDLE = ['-fPIC']
CXXFLAGS_cxxshlib = []
CXXLNK_SRC_F = []
CXXLNK_TGT_F = ['-o']
CXX_NAME = 'gcc'
CXX_SRC_F = []
CXX_TGT_F = ['-c', '-o']
DEFINES_ST = '-D%s'
DEST_BINFMT = 'pe'
DEST_CPU = 'x86'
DEST_OS = 'win32'
IMPLIB_ST = '-Wl,--out-implib,%s'
LIBDIR = 'C:\\users\\adrian~1\\appdata\\local\\temp/bin'
LIBPATH_ST = '-L%s'
LIB_ST = '-l%s'
LINKFLAGS = ['-Wl,--enable-auto-import']
LINKFLAGS_MACBUNDLE = ['-bundle', '-undefined', 'dynamic_lookup']
LINKFLAGS_cxxshlib = ['-shared']
LINKFLAGS_cxxstlib = ['-Wl,-Bstatic']
LINK_CXX = ['C:\\MinGW\\bin\\g++.exe']
PREFIX = 'C:\\users\\adrian~1\\appdata\\local\\temp'
RPATH_ST = '-Wl,-rpath,%s'
SHLIB_MARKER = '-Wl,-Bdynamic'
SONAME_ST = '-Wl,-h,%s'
STLIBPATH_ST = '-L%s'
STLIB_MARKER = '-Wl,-Bstatic'
STLIB_ST = '-l%s'
cxxprogram_PATTERN = '%s.exe'
cxxshlib_PATTERN = '%s.dll'
cxxstlib_PATTERN = 'lib%s.a'
implib_PATTERN = 'lib%s.dll.a'
macbundle_PATTERN = '%s.bundle'
